/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TruthPointRouteImport } from './routes/truth-point'
import { Route as TruthCoinRouteImport } from './routes/truth-coin'
import { Route as SudoCoinRouteImport } from './routes/sudo-coin'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeventhDimensionRouteImport } from './routes/seventh-dimension'
import { Route as SamCommandRouteImport } from './routes/sam-command'
import { Route as ReflectiveIntelRouteImport } from './routes/reflective-intel'
import { Route as ReclaimRouteImport } from './routes/reclaim'
import { Route as QuantotalusRouteImport } from './routes/quantotalus'
import { Route as ProofFulcrumRouteImport } from './routes/proof-fulcrum'
import { Route as PamRouteImport } from './routes/pam'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as NebulaRouteImport } from './routes/nebula'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DigitalOreRouteImport } from './routes/digital-ore'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthPointRoute = TruthPointRouteImport.update({
  id: '/truth-point',
  path: '/truth-point',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthCoinRoute = TruthCoinRouteImport.update({
  id: '/truth-coin',
  path: '/truth-coin',
  getParentRoute: () => rootRouteImport,
} as any)
const SudoCoinRoute = SudoCoinRouteImport.update({
  id: '/sudo-coin',
  path: '/sudo-coin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeventhDimensionRoute = SeventhDimensionRouteImport.update({
  id: '/seventh-dimension',
  path: '/seventh-dimension',
  getParentRoute: () => rootRouteImport,
} as any)
const SamCommandRoute = SamCommandRouteImport.update({
  id: '/sam-command',
  path: '/sam-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectiveIntelRoute = ReflectiveIntelRouteImport.update({
  id: '/reflective-intel',
  path: '/reflective-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclaimRoute = ReclaimRouteImport.update({
  id: '/reclaim',
  path: '/reclaim',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantotalusRoute = QuantotalusRouteImport.update({
  id: '/quantotalus',
  path: '/quantotalus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofFulcrumRoute = ProofFulcrumRouteImport.update({
  id: '/proof-fulcrum',
  path: '/proof-fulcrum',
  getParentRoute: () => rootRouteImport,
} as any)
const PamRoute = PamRouteImport.update({
  id: '/pam',
  path: '/pam',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulaRoute = NebulaRouteImport.update({
  id: '/nebula',
  path: '/nebula',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalOreRoute = DigitalOreRouteImport.update({
  id: '/digital-ore',
  path: '/digital-ore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-ore': typeof DigitalOreRoute
  '/fleet': typeof FleetRoute
  '/gateway': typeof GatewayRoute
  '/ledger': typeof LedgerRoute
  '/nebula': typeof NebulaRoute
  '/ops': typeof OpsRoute
  '/pam': typeof PamRoute
  '/proof-fulcrum': typeof ProofFulcrumRoute
  '/quantotalus': typeof QuantotalusRoute
  '/reclaim': typeof ReclaimRoute
  '/reflective-intel': typeof ReflectiveIntelRoute
  '/sam-command': typeof SamCommandRoute
  '/seventh-dimension': typeof SeventhDimensionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/sudo-coin': typeof SudoCoinRoute
  '/truth-coin': typeof TruthCoinRoute
  '/truth-point': typeof TruthPointRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-ore': typeof DigitalOreRoute
  '/fleet': typeof FleetRoute
  '/gateway': typeof GatewayRoute
  '/ledger': typeof LedgerRoute
  '/nebula': typeof NebulaRoute
  '/ops': typeof OpsRoute
  '/pam': typeof PamRoute
  '/proof-fulcrum': typeof ProofFulcrumRoute
  '/quantotalus': typeof QuantotalusRoute
  '/reclaim': typeof ReclaimRoute
  '/reflective-intel': typeof ReflectiveIntelRoute
  '/sam-command': typeof SamCommandRoute
  '/seventh-dimension': typeof SeventhDimensionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/sudo-coin': typeof SudoCoinRoute
  '/truth-coin': typeof TruthCoinRoute
  '/truth-point': typeof TruthPointRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-ore': typeof DigitalOreRoute
  '/fleet': typeof FleetRoute
  '/gateway': typeof GatewayRoute
  '/ledger': typeof LedgerRoute
  '/nebula': typeof NebulaRoute
  '/ops': typeof OpsRoute
  '/pam': typeof PamRoute
  '/proof-fulcrum': typeof ProofFulcrumRoute
  '/quantotalus': typeof QuantotalusRoute
  '/reclaim': typeof ReclaimRoute
  '/reflective-intel': typeof ReflectiveIntelRoute
  '/sam-command': typeof SamCommandRoute
  '/seventh-dimension': typeof SeventhDimensionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/sudo-coin': typeof SudoCoinRoute
  '/truth-coin': typeof TruthCoinRoute
  '/truth-point': typeof TruthPointRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digital-ore'
    | '/fleet'
    | '/gateway'
    | '/ledger'
    | '/nebula'
    | '/ops'
    | '/pam'
    | '/proof-fulcrum'
    | '/quantotalus'
    | '/reclaim'
    | '/reflective-intel'
    | '/sam-command'
    | '/seventh-dimension'
    | '/sitemap.xml'
    | '/status'
    | '/sudo-coin'
    | '/truth-coin'
    | '/truth-point'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digital-ore'
    | '/fleet'
    | '/gateway'
    | '/ledger'
    | '/nebula'
    | '/ops'
    | '/pam'
    | '/proof-fulcrum'
    | '/quantotalus'
    | '/reclaim'
    | '/reflective-intel'
    | '/sam-command'
    | '/seventh-dimension'
    | '/sitemap.xml'
    | '/status'
    | '/sudo-coin'
    | '/truth-coin'
    | '/truth-point'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/digital-ore'
    | '/fleet'
    | '/gateway'
    | '/ledger'
    | '/nebula'
    | '/ops'
    | '/pam'
    | '/proof-fulcrum'
    | '/quantotalus'
    | '/reclaim'
    | '/reflective-intel'
    | '/sam-command'
    | '/seventh-dimension'
    | '/sitemap.xml'
    | '/status'
    | '/sudo-coin'
    | '/truth-coin'
    | '/truth-point'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalOreRoute: typeof DigitalOreRoute
  FleetRoute: typeof FleetRoute
  GatewayRoute: typeof GatewayRoute
  LedgerRoute: typeof LedgerRoute
  NebulaRoute: typeof NebulaRoute
  OpsRoute: typeof OpsRoute
  PamRoute: typeof PamRoute
  ProofFulcrumRoute: typeof ProofFulcrumRoute
  QuantotalusRoute: typeof QuantotalusRoute
  ReclaimRoute: typeof ReclaimRoute
  ReflectiveIntelRoute: typeof ReflectiveIntelRoute
  SamCommandRoute: typeof SamCommandRoute
  SeventhDimensionRoute: typeof SeventhDimensionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  SudoCoinRoute: typeof SudoCoinRoute
  TruthCoinRoute: typeof TruthCoinRoute
  TruthPointRoute: typeof TruthPointRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth-point': {
      id: '/truth-point'
      path: '/truth-point'
      fullPath: '/truth-point'
      preLoaderRoute: typeof TruthPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth-coin': {
      id: '/truth-coin'
      path: '/truth-coin'
      fullPath: '/truth-coin'
      preLoaderRoute: typeof TruthCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudo-coin': {
      id: '/sudo-coin'
      path: '/sudo-coin'
      fullPath: '/sudo-coin'
      preLoaderRoute: typeof SudoCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seventh-dimension': {
      id: '/seventh-dimension'
      path: '/seventh-dimension'
      fullPath: '/seventh-dimension'
      preLoaderRoute: typeof SeventhDimensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sam-command': {
      id: '/sam-command'
      path: '/sam-command'
      fullPath: '/sam-command'
      preLoaderRoute: typeof SamCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflective-intel': {
      id: '/reflective-intel'
      path: '/reflective-intel'
      fullPath: '/reflective-intel'
      preLoaderRoute: typeof ReflectiveIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclaim': {
      id: '/reclaim'
      path: '/reclaim'
      fullPath: '/reclaim'
      preLoaderRoute: typeof ReclaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantotalus': {
      id: '/quantotalus'
      path: '/quantotalus'
      fullPath: '/quantotalus'
      preLoaderRoute: typeof QuantotalusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-fulcrum': {
      id: '/proof-fulcrum'
      path: '/proof-fulcrum'
      fullPath: '/proof-fulcrum'
      preLoaderRoute: typeof ProofFulcrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pam': {
      id: '/pam'
      path: '/pam'
      fullPath: '/pam'
      preLoaderRoute: typeof PamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebula': {
      id: '/nebula'
      path: '/nebula'
      fullPath: '/nebula'
      preLoaderRoute: typeof NebulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-ore': {
      id: '/digital-ore'
      path: '/digital-ore'
      fullPath: '/digital-ore'
      preLoaderRoute: typeof DigitalOreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalOreRoute: DigitalOreRoute,
  FleetRoute: FleetRoute,
  GatewayRoute: GatewayRoute,
  LedgerRoute: LedgerRoute,
  NebulaRoute: NebulaRoute,
  OpsRoute: OpsRoute,
  PamRoute: PamRoute,
  ProofFulcrumRoute: ProofFulcrumRoute,
  QuantotalusRoute: QuantotalusRoute,
  ReclaimRoute: ReclaimRoute,
  ReflectiveIntelRoute: ReflectiveIntelRoute,
  SamCommandRoute: SamCommandRoute,
  SeventhDimensionRoute: SeventhDimensionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  SudoCoinRoute: SudoCoinRoute,
  TruthCoinRoute: TruthCoinRoute,
  TruthPointRoute: TruthPointRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
